### ISSUE TITLE
hq-engineering should take over ownership of draw-dino

### ISSUE THREAD

**Issue by grymmy** [hackclub/infra#39]
hq-engineering should take official maintainership of hackclub/draw-dino.  This means the following:

```[tasklist]
### Tasks
- [x] Create a slacker maintainers file w/ appropriate configuration
- [x] Add instrumentation to the site
- [x] Create grafana dashboard
- [x] Create grafana alerts
- [x] Create a simple maintenance runbook
```

**Comment by grymmy** [comment]
Message to myself in the future - this issue had better not ping anymore (clawback should be disabled).

**Comment by grymmy** [comment]
🥇
